version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: chronic-tracker-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chronic-tracker
    volumes:
      - mongodb_data:/data/db
    networks:
      - chronic-tracker-network

  mongo-express:
    image: mongo-express:latest
    container_name: chronic-tracker-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - chronic-tracker-network

networks:
  chronic-tracker-network:
    driver: bridge

volumes:
  mongodb_data:
